Review 1 (#2)
* Add custom User model (#1)

* Add custom User model

* Fix redoc

* Registration and tokens (#14)

* Add custom User model

* Fix redoc

* First attempt at registration

* Fix tests

* Simplify sign-up serialization code

* User control and permissions (#15)

* Add all user-related endpoints

* Add two permissions

* Simplify UserMeSerializer (#16)

* add text for text to README (#17)

* Split me action into two methods (#18)

* Feature/titles (#19)

* Добавление моделей Title, Сategory, Genre
и структуры api

* Добавление сериализаторов...
- CategoriesSerializer
- GenresSerializer
- TitlesPostSerializer
- TitlesPostSerializer

* Создание моделей, сериализаторов, вьюх, урлов для
- Названий произведений
- Названий жанров произведений
- Названий категорий произведений
pytest пишет о 6 ошибках:
FAILED tests/test_02_category.py::Test02CategoryAPI::test_02_category_with_admin_user - AssertionError: Проверьте, что для эндпоинта `/api/v1/categories/` настроена пагинация. Значение параметра `results` отсутствует или содержит некорректную информацию о существующем объекте.
FAILED tests/test_02_category.py::Test02CategoryAPI::test_04_category_delete_admin - AssertionError: Проверьте, что DELETE-запрос администратора к `/api/v1/categories/{slug}/` возвращает ответ со статусом 204.
FAILED tests/test_03_genre.py::Test03GenreAPI::test_02_genre - AssertionError: Проверьте, что для эндпоинта `/api/v1/genres/` настроена пагинация. Значение параметра `results` отсутствует или содержит некорректную информацию о существующем объекте.
FAILED tests/test_03_genre.py::Test03GenreAPI::test_04_genres_delete - AssertionError: Проверьте, что DELETE-запрос администратора к `/api/v1/genres/{slug}/` возвращает ответ со  статусом 204.
FAILED tests/test_04_title.py::Test04TitleAPI::test_02_title_admin - AttributeError: 'Title' object has no attribute 'reviews'
FAILED tests/test_04_title.py::Test04TitleAPI::test_03_titles_detail - AttributeError: 'Title' object has no attribute 'reviews'

* bugfix_v1
List bugs for next bug fix:
FAILED tests/test_02_category.py::Test02CategoryAPI::test_04_category_delete_admin - AssertionError: Проверьте, что DELETE-запрос администратора к `/api/v1/categories/{slug}/` возвращает ответ со статусом 204.
FAILED tests/test_03_genre.py::Test03GenreAPI::test_04_genres_delete - AssertionError: Проверьте, что DELETE-запрос администратора к `/api/v1/genres/{slug}/` возвращает ответ со  статусом 204.
FAILED tests/test_04_title.py::Test04TitleAPI::test_02_title_admin - AttributeError: 'Title' object has no attribute 'reviews'
FAILED tests/test_04_title.py::Test04TitleAPI::test_03_titles_detail - AttributeError: 'Title' object has no attribute 'reviews'

* bugfix_v2

* bugfix_v2.1

* Minor fixes for text and class names (#21)

* Feature/reviews (#22)

* add text for text to README

* deleted one line in Readme

* delete one line from Readme

* Add model Review, ReviewSerializer, ReviewVeiwSet

* make migrations, small corrections

* Add one symbol for test

Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention

* Add model Comment

+ Small changes on views and urls

* Add README.md and black configuration (#23)

* Add a migration and black settings

* Run black/isort on the project

* Add README.md

* Add a note about python3

* Feature/bulkload (#25)

* Добавление моделей Title, Сategory, Genre
и структуры api

* Добавление сериализаторов...
- CategoriesSerializer
- GenresSerializer
- TitlesPostSerializer
- TitlesPostSerializer

* Создание моделей, сериализаторов, вьюх, урлов для
- Названий произведений
- Названий жанров произведений
- Названий категорий произведений
pytest пишет о 6 ошибках:
FAILED tests/test_02_category.py::Test02CategoryAPI::test_02_category_with_admin_user - AssertionError: Проверьте, что для эндпоинта `/api/v1/categories/` настроена пагинация. Значение параметра `results` отсутствует или содержит некорректную информацию о существующем объекте.
FAILED tests/test_02_category.py::Test02CategoryAPI::test_04_category_delete_admin - AssertionError: Проверьте, что DELETE-запрос администратора к `/api/v1/categories/{slug}/` возвращает ответ со статусом 204.
FAILED tests/test_03_genre.py::Test03GenreAPI::test_02_genre - AssertionError: Проверьте, что для эндпоинта `/api/v1/genres/` настроена пагинация. Значение параметра `results` отсутствует или содержит некорректную информацию о существующем объекте.
FAILED tests/test_03_genre.py::Test03GenreAPI::test_04_genres_delete - AssertionError: Проверьте, что DELETE-запрос администратора к `/api/v1/genres/{slug}/` возвращает ответ со  статусом 204.
FAILED tests/test_04_title.py::Test04TitleAPI::test_02_title_admin - AttributeError: 'Title' object has no attribute 'reviews'
FAILED tests/test_04_title.py::Test04TitleAPI::test_03_titles_detail - AttributeError: 'Title' object has no attribute 'reviews'

* bugfix_v1
List bugs for next bug fix:
FAILED tests/test_02_category.py::Test02CategoryAPI::test_04_category_delete_admin - AssertionError: Проверьте, что DELETE-запрос администратора к `/api/v1/categories/{slug}/` возвращает ответ со статусом 204.
FAILED tests/test_03_genre.py::Test03GenreAPI::test_04_genres_delete - AssertionError: Проверьте, что DELETE-запрос администратора к `/api/v1/genres/{slug}/` возвращает ответ со  статусом 204.
FAILED tests/test_04_title.py::Test04TitleAPI::test_02_title_admin - AttributeError: 'Title' object has no attribute 'reviews'
FAILED tests/test_04_title.py::Test04TitleAPI::test_03_titles_detail - AttributeError: 'Title' object has no attribute 'reviews'

* bugfix_v2

* bugfix_v2.1

* Add csv bulkload

* save after merge

* refactoring load.py

* Refactor urls to reduce prefix duplication (#26)

* Feature/comments (#24)

* add text for text to README

* deleted one line in Readme

* delete one line from Readme

* Add model Review, ReviewSerializer, ReviewVeiwSet

* make migrations, small corrections

* Add one symbol for test

Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention
Just test. don't pay attention

* Add model Comment

+ Small changes on views and urls

* add docstring to models and add CommentSerializer

add docstring to models and add CommentSerializer to serializers

* Add CommentViewSet

* Add urls for Comments

+small format changes in models and views.

* Add constrains to Review model

Make migrations
add Validator to ReviewSerializer

* Add small changes.

* Accept changes in Readme

* Correct after review.

views and serializers

* Feature/rating (#27)

* Remove unused import

---------

Co-authored-by: Dmitry <monk-time@users.noreply.github.com>
Co-authored-by: LenarFazlyev <121536686+LenarFazlyev@users.noreply.github.com>